### PR TITLE
Bump AsyncKeyedLock to 7.1.3

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**

### CODE REVIEW

**Comment by VahidN** [comment]
Test Run Failed.
Total tests: 499
     Passed: 463
     **Failed: 36**

**Comment by MarkCiliaVincenti** [comment]
By the way, I need to analyze your code better. I cannot understand how what happened happened because I couldn't replicate with my tests.

For some reason, the value of AsyncNonKeyedLocker in AsyncNonKeyedLockReleaser was null so I reverted:

_locker._semaphoreSlim.Release();

to:

_locker?._semaphoreSlim.Release();

**Comment by MarkCiliaVincenti** [comment]
@VahidN I could only replicate with this:

            AsyncNonKeyedLockReleaser releaser = new();
            releaser.Dispose();
            
You are not supposed to be creating instances of AsyncNonKeyedLockReleaser. This shows a problem with your implementation/tests.

https://github.com/MarkCiliaVincenti/AsyncKeyedLock/blob/master/AsyncKeyedLock/AsyncNonKeyedLockReleaser.cs

Can you please look into it?

**Comment by VahidN** [comment]
Yes, I changed it to use the new methods.

**Comment by MarkCiliaVincenti** [comment]
> Yes, I changed it to use the new methods.

What do you mean please?

**Comment by MarkCiliaVincenti** [comment]
Ah, you introduced a timeout, I see

**Pull request merged**
